language: node_js

node_js:
  - 8.11.1

install:
  - npm install

script:
  - npm run test:unit -- --coverage && npm run test:snapshot -- --coverage

after_script:
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coveralls